In [1]:
#import NumPy
import numpy as np

In [2]:
list1 = list([1,2,3,4,5,6])
array1 = np.array([1,2,3,4,5,6])

In [3]:
print(list1)
print(array1)

[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]


In [4]:
print(type(list1))
print(type(array1))

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
#Simple Array
array1 = np.array((1,2,3,4,5))
print(type(array1))

<class 'numpy.ndarray'>


In [5]:
#Multi-dimensional Arrays 1-D,2-D,3-D
array1 = np.array(15)
array1D = np.array([1,2,3,4,5])
array2D = np.array([[1,2,3],[4,5,6]])
array3D = np.array([[[1.6,2.2,3],[3,4,5]],[[5,6,7],[7,8,9]]])
print(array1D)
print(array2D)
print(array3D)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1.6 2.2 3. ]
  [3.  4.  5. ]]

 [[5.  6.  7. ]
  [7.  8.  9. ]]]


In [10]:
#Numpy Attributes (shape, size, dtype, ndim, astype, itemsize)
print(array2D.shape)
print(array3D.size)
print(array3D.dtype)
print(array2D.ndim)
print(array2D.astype(float))
print(array2D.itemsize)

(2, 3)
12
float64
2
[[1. 2. 3.]
 [4. 5. 6.]]
8


In [ ]:
array1 = np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]])
print(array1)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [18]:
import numpy as np
array1 = np.eye(5,5,-2,dtype=int)
print(array1)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]]


In [ ]:
#NumPy functions (eye, ones, zeros, linspace, arange )
array1 = np.eye(5,5,4)
print(array1)
array1 = np.ones((3,3), dtype=int)
print(array1)
array1 = np.zeros((3,4), dtype=int)
print(array1)

[[0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [24]:
a = list(range(2,15,2))
print(a)

[2, 4, 6, 8, 10, 12, 14]


In [30]:
array2 = np.arange(18).reshape(2,3,3)
#array2 = array2.reshape(3,3)
print(array2)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]


In [31]:
array3 = np.linspace(2,20,4)
print(array3)

[ 2.  8. 14. 20.]


In [32]:
import numpy as np
array1 = np.array([1,2,3,4,5,6,7,8,9])

In [33]:
print(sum(array1)) #sum, min, max, len

45


In [34]:
array2D

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
array2D.sum(axis=0)

array([5, 7, 9])

In [63]:
array1 = np.arange(12).reshape(2,2,3)
print(array1)
print("Ans:- \n",array1[:,:])

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
Ans:- 
 [[ 1  4]
 [ 7 10]]


In [ ]:
array1 = np.arange(9).reshape(3,3)
print(array1)
array1.sum(axis=0)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([ 9, 12, 15])

In [64]:
#Arithmetic Operations
a = np.arange(1,10)#.reshape(3,3)
b = np.arange(10,19)
print(a)
print(b)

[1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18]


In [65]:
c = a+b
print(c)
d = b-a
print(d)
e = b*a
print(e)
f = b/a
print(f)

[11 13 15 17 19 21 23 25 27]
[9 9 9 9 9 9 9 9 9]
[ 10  22  36  52  70  90 112 136 162]
[10.          5.5         4.          3.25        2.8         2.5
  2.28571429  2.125       2.        ]


In [ ]:
a = np.arange(1,10)
b = np.arange(10,20)
array2 = np.arange(1000)
array2.itemsize

8

In [ ]:
import numpy as np
array1 = np.arange(25).reshape(5,5)
print(array1)
print("\n Ans:-",array1[0:,1:3])
#print("\n Ans:-",array1[0:2,0:2,0:2])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

 Ans:- [[ 1  2]
 [ 6  7]
 [11 12]
 [16 17]
 [21 22]]


In [ ]:
import numpy as np

In [ ]:
new1 = np.arange(18).reshape(3,3,2)
print(new1)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]]


In [ ]:
new1[1,1:,:]

array([[ 8,  9],
       [10, 11]])

In [ ]:
#Indexing and slicing
new1 = np.arange(1,13).reshape(3,4)
print(new1)
#print("Ans:-", new1[0:2,0:2])
#print("Ans:-", new1[0,0,0],new1[0,1,2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Ans:- [[1 2]
 [5 6]]


In [ ]:
new1 = np.arange(25).reshape(5,5)
print(new1)
new1.diagonal(-1)
#print("Ans:-", new1[2,2,1])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([ 5, 11, 17, 23])

In [ ]:
new1= np.arange(16).reshape(4,4)

In [ ]:
print(new1)
print(new1.diagonal())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[ 4  9 14]


In [66]:
#Python list vs np.array
#memory
import numpy as np
import sys
list1 = list(range(1000))
print(sys.getsizeof(list1[10])*len(list1))

array = np.arange(1000)
print(array.size*array.itemsize)

28000
8000


In [68]:
#Speed
import time
size = 100000000

list1 = range(size)
list2 = range(size)
array1 = np.arange(size)
array2 = np.arange(size)

start = time.time()
result_list = [list1[i] + list2[i] for i in range(size)]
print(f"List addition time: {time.time() - start:.6f} seconds")

start = time.time()
result_array = array1 + array2
print(f"Array addition time: {time.time() - start:.6f} seconds")

List addition time: 0.000058 seconds
Array addition time: 0.126913 seconds


In [ ]:
#Broadcasting & Upcasting
import numpy as np

In [ ]:
A = np.arange(12).reshape(3,4)
B = np.arange(4)
print("Array1 : \n",A)
print("Array2 : \n",B)
C = A + B
print("Array3 Ans :\n",C)

Array1 : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Array2 : 
 [0 1 2 3]
Array3 Ans :
 [[ 0  2  4  6]
 [ 4  6  8 10]
 [ 8 10 12 14]]


In [ ]:
A = np.arange(12).reshape(3,4)
B = np.array([[1],[2],[3]])
print("Array1 : \n",A)
print("Array2 : \n",B)
C = A + B
print("Array3 Ans :\n",C)

Array1 : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Array2 : 
 [[1]
 [2]
 [3]]
Array3 Ans :
 [[ 1  2  3  4]
 [ 6  7  8  9]
 [11 12 13 14]]


In [ ]:
A = np.arange(24).reshape(4,6)
A

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [ ]:
B = np.array([3,3,4,2,1,2])
B.shape

(6,)

In [ ]:
new = A+B
print(A)
print(B)
print(new)
print(B.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[3 3 4 2 1 2]
[[ 3  4  6  5  5  7]
 [ 9 10 12 11 11 13]
 [15 16 18 17 17 19]
 [21 22 24 23 23 25]]
(6,)


In [ ]:
C = np.array([[1],[2],[3],[4]])
C

array([[1],
       [2],
       [3],
       [4]])

In [ ]:
print(A)
print(C)
print(A+C)


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[1]
 [2]
 [3]
 [4]]
[[ 1  2  3  4  5  6]
 [ 8  9 10 11 12 13]
 [15 16 17 18 19 20]
 [22 23 24 25 26 27]]


In [ ]:
A = np.array([[1,2,30],[4,5,6],[7,8,9]])
B = np.array([[5.5,3.2,4.2],[1.4,2.5,7.6],[7.8,8.7,1.8]])
C= A+B
C

[[ 1  2 30]
 [ 4  5  6]
 [ 7  8  9]]


array([[ 6.5,  5.2, 34.2],
       [ 5.4,  7.5, 13.6],
       [14.8, 16.7, 10.8]])

In [ ]:
array1 = np.array([[10,12,15],[21,31,20],[31,12,12]])
print(array1)

demo = array1 == 12
print(demo)

array1[demo] = 30
print(array1)

[[10 12 15]
 [21 31 20]
 [31 12 12]]
[[False False False]
 [ True  True False]
 [ True False False]]
[[10 12 15]
 [50 50 20]
 [50 12 12]]


In [ ]:
import numpy as np
x1 = np.arange(1,10).reshape(3,3)
print(x1)

demo = x1<5
print(demo)

x1[demo] = x1[demo]*2
print(x1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ True  True  True]
 [ True False False]
 [False False False]]
[[2 4 6]
 [8 5 6]
 [7 8 9]]


In [74]:
array1 = np.array([[10,12,15],[21,31,20],[31,12,12]])
print(array1)

dummy = array1 < 15
print(dummy)

array1[dummy] = 50
print(array1)

[[10 12 15]
 [21 31 20]
 [31 12 12]]
[[ True  True False]
 [False False False]
 [False  True  True]]
[[50 50 15]
 [21 31 20]
 [31 50 50]]


In [ ]:
(3/10)*100

30.0

In [82]:
x1 = np.arange(1

  ,10).reshape(3,3)
print(x1)

d1 = x1<6
print(d1)

x1[d1] = x1[d1]*x1[d1]
print(x1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ True  True  True]
 [ True  True False]
 [False False False]]
[[ 1  4  9]
 [16 25  6]
 [ 7  8  9]]


In [ ]:
print(A)
c1 = A==5
print(c1)
5000*55

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False False False]
 [False  True False]
 [False False False]]


275000

In [ ]:
A[c1] = A[c1]+8

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
c2 = A>5
A[c2] = A[c2]*2

In [ ]:
print(A)

[[ 1  2  3]
 [ 4  5 12]
 [14 16 18]]


In [ ]:
new1 = np.random.randint(10,15,(5,5))
new2 = np.random.uniform(2,5,(4,3))
print(new1)
print(new2)

[[14 13 10 14 14]
 [13 11 12 11 11]
 [13 14 11 10 12]
 [14 13 12 12 10]
 [14 14 10 12 11]]
[[4.88397934 3.17515712 3.380674  ]
 [2.10213858 4.69520998 4.43650853]
 [3.63377901 3.39342247 4.71342841]
 [4.33764676 4.07849101 3.0484136 ]]


In [ ]:
def custom_func(i, j): #(i or j) value 0 to n tak
    return i + j

arr = np.fromfunction(custom_func, (5, 5), dtype=int) #fromfunction for value getting from the funti

In [ ]:
arr

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

In [ ]:
import numpy as np

In [ ]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A)
#B = np.array([[[1,2],[2,3],[3,4]],[[5,6],[6,7],[7,8]]])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
A1 = A
print(A1)
q1 = A1.flatten()
print(q1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [ ]:
A2 = A
print(A2)
q2 = A2.ravel()
print(q2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [ ]:
print(A1)
print(q1)
q1[0] = 22
print(A1)
print(q1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[22  2  3  4  5  6  7  8  9]


In [ ]:
print(A2)
print(q2)
q2[0] = 23
print(A2)
print(q2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[[23  2  3]
 [ 4  5  6]
 [ 7  8  9]]
[23  2  3  4  5  6  7  8  9]


In [ ]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
B = A.ravel()
print(B)

[1 2 3 4 5 6 7 8 9]


In [ ]:
B[0] = 10

In [ ]:
print(A)

[[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [ ]:
import numpy as np
array1 =  np.arange(24).reshape(2,3,4)
print(array1)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
array1[1,1,2] = 50

In [ ]:
array1

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 50, 19],
        [20, 21, 22, 23]]])